import 'package:denukan_business_solutions/ServiceClass.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'Welcome.dart';

const kPrimaryColor = Color(0xff55c282);
const kBackgroundHome4 = Color(0xFFE8EDF2);
const kBackgroundHome3 = Color(0xFFFCF8FD);
const kBackgroundHome2 = Color(0xFFF7F5FC);
const kBackgroundHome = Color(0xFF1836EB);
const kpurpleColor = Color(0xFF8D28AD);
//const kPrimaryColor = Color(0xFFC926B4);
const kSecondaryColor = Color(0xFF00D1FF);
const kTettiaryColor1 = Color(0xFF0007A9);
const kfacebookColor = Color(0xFF4267B2);
const kgoogleColor = Color(0xFFD0021B);
const kTettiaryColor2 = Color(0xFFAD00FF);
const kTettiaryColor3 = Color(0xFFFF3D00);
const kContentColorDarkTheme = Color(0xFFF5FCF9);
const kWarninngColor = Color(0xFFF3BB1C);
const kErrorColor = Color(0xFFF03738);
Color kColorSmoke = const Color(0xffC0C0C0);
Color kColorSmoke2 = const Color(0xff878685);
Color kColorWhite = Colors.white;
Color kColorShade = const Color(0xfff5f5f5);
const kColorBlack = Color(0xFF1D1D35);
